### PR TITLE
Build(Dockerfile): Compile with LTO, and strip

### PR DESCRIPTION
**Pull request by ee7**
This PR adds compilation/linking flags that make the `runner` binary smaller and faster.

### CODE REVIEW

**Review by ynfle — APPROVED** [review]
I'd add somewhere what the flags do b/c I don't think they're documented.

Not required for merging though

**Comment by ee7** [comment]
> I'd add somewhere what the flags do b/c I don't think they're documented.

Good idea - they're definitely under-documented at the moment. It's on the website though, see:
- https://github.com/nim-lang/website/commit/00ff559652a6b44298ad98e38a08703b02eafd21
- https://nim-lang.org/faq.html (Ctrl + f lto) 

And they're defined [here](https://github.com/nim-lang/Nim/blob/fa5f225efc7161110b0d4cf57e86646f2b0d97f8/config/nim.cfg#L331-L361).

I'll just document it in the commit message for now.

**Comment by ynfle** [comment]
Those are none of the places that I would have looked for compilation options, and that is the reason that I was confused about what they were. I would have assumed them to be somewhere else like [here](https://nim-lang.org/docs/nimc.html)

**Comment by ee7** [comment]
> I would have assumed them to be somewhere else like [here](https://nim-lang.org/docs/nimc.html)

Yes, I'd expect it there too, given that's where `--passC:-flto` is mentioned.

It looks like part of the reason that `-d:lto` is under-documented is that it doesn't work properly on macOS yet. See [here](https://github.com/nim-lang/Nim/issues?q=-d%3Alto).

It might've been better if this PR just did `--passC:-flto --passL:-s`, but:
- we're only using `-d:lto` on Linux
- and as mentioned, the source of truth is [nim.cfg](https://github.com/nim-lang/Nim/blob/fa5f225efc7161110b0d4cf57e86646f2b0d97f8/config/nim.cfg#L331-L361) where we can see that for us it really is just doing
```
--passC:-flto --passL:-flto --passL:-s
```

(`--passL:-flto` is only needed for pretty ancient versions of `gcc`).

**Pull request merged**
