### PR TITLE
Feature(runner): capture output

### LINKED ISSUE #13: Feature: Capturing submission output
# Issue
In keeping with [the interface](https://github.com/exercism/automated-tests/blob/master/docs/interface.md), the test runner needs to expose a way for the user to deliberately output debugging or other information from their code.

## Solutions
1. Capture `stdout` and let the user use `echo`
   1. Wouldn't work for threads
    2. We could let the user call echo and then manipulate the call to directly capture it
2. Expose a new proc (ex. `debug`), with the same interface as echo, that we can use to directly capture the output  
    1. It seems like we'd either have `include` the submitted code into the test file or have a macro that reads their code and puts it in the test file. 
     2. The issue is that the line numbers are for the combined file, not theirs, which isn't much of an issue if we are going to sanitize the stacktraces anyways
    

## Prior Art
- [Python](https:/github.com/exercims/python-test-runner)
  - Uses pytest's native output capturing capabilities _(Not implemented in unittest)_
- [Elixir](https:/github.com/exercims/elixir-test-runner)
  - Outputs a start and stop identifier to stdout for each test and then captures that output that is in between the the identifiers (as per [this](https://exercism-team.slack.com/archives/CMNQSQZUY/p1590976295042100) conversation in Slack)
- [Ruby](https:/github.com/exercims/ruby-test-runner)
  - Adds a method in the global scope to directly capture user output

### PR DESCRIPTION
**Pull request by ynfle**
Supersedes #26 (my mess up because I deleted my fork before this was merged)
Closes #13 

- Feature(unittest_json): add messages when tests start and finish
- Feature(runner): capture output
- Fix(runner): use native JsonNode instead of the type
- Test(runner): test capturing `stdout` & `stderr` and writing to json
- Fix(runner): include trailing whitespace from output
- Fix(runner): truncate user output for unicode lenght of 500 with message
- Test(runner): test for truncation message and unicode length
- Fix: Fix typo in directory name
- Test: Remove `fail/multiple_tests_one_fail` output cases
- Test: Remove `fail/multiple_tests_all_fail` output case
- Test: Use `proc` instead of `func` and `debugEcho`
- Test: Improve `pass/single_test_output` case
- Test: Improve `pass/multiple_tests_output_truncated`
- Test: Improve `pass/multiple_tests_output_unicode_truncated`
- Refactor: Nitpick style
- Refactor(runner): Simplify result assignment from `execCmdEx`
- Refactor(unittest_json): Remove export markers again
- Fix(runner): Fix return type in `run` proc doc comment
- Refactor(runner): Change a misleading `let` to a `var`
- Fix(runner): Don't truncate output that has rune-length of 500
- Test: Improve `pass/single_test_output_unicode`
- Test: Add `pass/single_test_output_stderr_only`

### CODE REVIEW

**Comment by iHiD** [comment]
Thank you for this! 💙 

@ee7 is knee-deep in Conflgiet atm (which I imagine is going to take their time up till launch) so I suggest that if you're broadly happy with this, we just get it merged down and then any improvements can be made later, rather than get too caught up in review cycles at this stage. I've therefore tagged @ErikSchierboom who can maybe give it a quick sanity check for you for now! :)

**Comment by ynfle** [comment]
@ee7 Had a requested a bunch of stuff that was requested and PRed on my branch (which I, unthoughtfully, deleted without waiting until this PR was merged) which can always be addressed later. @ee7, what do you think?

**Comment by ee7** [comment]
> we just get it merged down and then any improvements can be made later, rather than get too caught up in review cycles at this stage

The main part of the review is done. I just need to do a couple of things to fix this PR. Don't merge this yet.

I think I'll be able to merge this within the next 24 hours.

**Comment by ynfle** [comment]
> > we just get it merged down and then any improvements can be made later, rather than get too caught up in review cycles at this stage
> 
> The main part of the review is done. I just need to do a couple of things to fix this PR. Don't merge this yet.
> 
> I think I'll be able to merge this within the next 24 hours.

I rebased on main. What were you planning on fixing?

**Comment by ee7** [comment]
> . What were you planning on fixing?

First I'll make CI green again - it's [currently failing on this PR](https://github.com/exercism/nim-test-runner/pull/48/checks?check_run_id=1846460952). 

See https://github.com/exercism/nim-test-runner/pull/49.

Then I'll make it so the new test cases actually run. Currently they're silently skipped - scroll down [here](https://github.com/exercism/nim-test-runner/pull/48/checks?check_run_id=1846455334#step:4:38) and notice that, although the check is green, no output capture tests actually ran.

**Comment by ee7** [comment]
Ping @iHiD - can you review this one too?

I'm setting this back to draft because I see:
> Merging can be performed automatically with 1 approving review.

But I don't want automatic merging here - I want to merge this.

**Review by iHiD — APPROVED** [review]

**Review by ee7 — APPROVED** [review]

**Pull request merged**
