### PR TITLE
Feature(runner): capture output

### LINKED ISSUE #13: Feature: Capturing submission output
# Issue
In keeping with [the interface](https://github.com/exercism/automated-tests/blob/master/docs/interface.md), the test runner needs to expose a way for the user to deliberately output debugging or other information from their code.

## Solutions
1. Capture `stdout` and let the user use `echo`
   1. Wouldn't work for threads
    2. We could let the user call echo and then manipulate the call to directly capture it
2. Expose a new proc (ex. `debug`), with the same interface as echo, that we can use to directly capture the output  
    1. It seems like we'd either have `include` the submitted code into the test file or have a macro that reads their code and puts it in the test file. 
     2. The issue is that the line numbers are for the combined file, not theirs, which isn't much of an issue if we are going to sanitize the stacktraces anyways
    

## Prior Art
- [Python](https:/github.com/exercims/python-test-runner)
  - Uses pytest's native output capturing capabilities _(Not implemented in unittest)_
- [Elixir](https:/github.com/exercims/elixir-test-runner)
  - Outputs a start and stop identifier to stdout for each test and then captures that output that is in between the the identifiers (as per [this](https://exercism-team.slack.com/archives/CMNQSQZUY/p1590976295042100) conversation in Slack)
- [Ruby](https:/github.com/exercims/ruby-test-runner)
  - Adds a method in the global scope to directly capture user output

### PR DESCRIPTION
**Pull request by ynfle**
Getting ready for research project deployment!!!
- Feature(unittest_json): add messages when tests start and finish
- Feature(runner): capture output
- Fix(runner): use native JsonNode instead of the type
- Test(runner): test capturing `stdout` & `stderr` and writing to json

Closes #13

### CODE REVIEW

**Comment by ynfle** [comment]
Message truncation (and Unicode support) are coming...

**Comment by ynfle** [comment]
Rebased to fix conflict with master b/c of #24

**Comment by ee7** [comment]
Looks good.

I have some suggested changes. It was easier for me to review by making a PR to your branch. See https://github.com/ynfle/nim-test-runner/pull/1.

**Comment by ee7** [comment]
Now we just have to rebase on `main` and reflect some changes that happened in the meantime so that the tests pass again.

I'll do it soon.

**Comment by ynfle** [comment]
So I deleted my fork (I stopped using forks if I have write access to a repo and just use a branch) so I have to move this to a new branch.

**Pull request closed without merging**
